services:
  postgres:
    image: postgres:16
    container_name: retail_sales_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: retail_sales
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - retail_sales_pgdata:/var/lib/postgresql/data

volumes:
  retail_sales_pgdata:
